# Generated by Django 2.2.16 on 2022-12-03 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_auto_20221203_2051'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='subs',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'following')},
        ),
    ]
