# Generated by Django 2.2.16 on 2022-12-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20221203_2152'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(
                fields=('user_id', 'following_id'), name='unique_user_following'),
        ),
    ]
